// <auto-generated />
using System;
using Joki.Infraestructura.AccesoDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Joki.Infraestructura.Migrations
{
    [DbContext(typeof(JokiContext))]
    [Migration("20260609200610_DescuentosConfigurables")]
    partial class DescuentosConfigurables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int?>("AlumnoUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoUsuarioId");

                    b.HasIndex("ClaseId");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("AlumnoId", "ClaseId", "Fecha")
                        .IsUnique();

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidad", "EntidadId");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Beneficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionBeneficio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DescuentoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MesesAplicados")
                        .HasColumnType("int");

                    b.Property<int>("MesesDuracion")
                        .HasColumnType("int");

                    b.Property<int?>("RecompensaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("DescuentoId");

                    b.HasIndex("RecompensaId");

                    b.ToTable("Beneficio", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("int");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EsFija")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<decimal>("RadioGeolocalizacion")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId", "DiaSemana", "HoraInicio");

                    b.ToTable("Clase", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clase_Cupo", "[CupoMaximo] > 0");

                            t.HasCheckConstraint("CK_Clase_Fechas", "[FechaFin] IS NULL OR [FechaFin] >= [FechaInicio]");

                            t.HasCheckConstraint("CK_Clase_Horario", "[HoraFin] > [HoraInicio]");
                        });
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.ConfiguracionCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoMensual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesCuota");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId", "Mes", "Anio")
                        .IsUnique();

                    b.ToTable("Cuota", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Desafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FechaInicio");

                    b.ToTable("Desafio", null, t =>
                        {
                            t.HasCheckConstraint("CK_Desafio_Fechas", "[FechaFin] >= [FechaInicio]");
                        });
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Alcance")
                        .HasColumnType("int");

                    b.Property<int?>("DesafioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesesDuracion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Grupo", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("AlumnoId", "ClaseId")
                        .IsUnique();

                    b.ToTable("Inscripcion", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.ListaEspera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ClaseId");

                    b.ToTable("ListaEspera");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.MaterialEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("MaterialEjercicio", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("Leida");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuotaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuotaId");

                    b.HasIndex("FechaPago");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.ParticipacionDesafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("DesafioId")
                        .HasColumnType("int");

                    b.Property<bool>("Ganador")
                        .HasColumnType("bit");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId");

                    b.HasIndex("AlumnoId", "DesafioId")
                        .IsUnique();

                    b.ToTable("ParticipacionDesafio", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DesafioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId");

                    b.ToTable("Recompensa", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.RecuperacionContrasena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RecuperacionesContrasena");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.SolicitudCupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("AlumnoId", "ClaseId")
                        .IsUnique();

                    b.HasIndex("ClaseId", "Orden")
                        .IsUnique();

                    b.ToTable("SolicitudCupo", (string)null);
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.TokenRevocado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TokensRevocados");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProveedorAutenticacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SociedadMedica")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Alumno", b =>
                {
                    b.HasBaseType("Usuario");

                    b.Property<int>("AnioRachaAsistencia")
                        .HasColumnType("int");

                    b.Property<bool>("BloqueadoPorInasistencias")
                        .HasColumnType("bit");

                    b.Property<bool>("DescuentoRachaGenerado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Estatura")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("IMC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MesRachaAsistencia")
                        .HasColumnType("int");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RachaAsistenciaMensual")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Alumno");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Entrenador", b =>
                {
                    b.HasBaseType("Usuario");

                    b.HasDiscriminator().HasValue("Entrenador");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Asistencia", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("AlumnoUsuarioId");

                    b.HasOne("Joki.LogicaNegocio.Entidades.Clase", "Clase")
                        .WithMany("Asistencias")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Auditoria", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Beneficio", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", "Alumno")
                        .WithMany("Beneficios")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joki.LogicaNegocio.Entidades.Descuento", "Descuento")
                        .WithMany()
                        .HasForeignKey("DescuentoId");

                    b.HasOne("Joki.LogicaNegocio.Entidades.Recompensa", "Recompensa")
                        .WithMany("Beneficios")
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("Descuento");

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Clase", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Grupo", "Grupo")
                        .WithMany("Clases")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Joki.LogicaNegocio.ValueObjects.Ubicacion", "Ubicacion", b1 =>
                        {
                            b1.Property<int>("ClaseId")
                                .HasColumnType("int");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CodigoPostal");

                            b1.Property<decimal>("Latitud")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Latitud");

                            b1.Property<decimal>("Longitud")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Longitud");

                            b1.HasKey("ClaseId");

                            b1.ToTable("Clase");

                            b1.WithOwner()
                                .HasForeignKey("ClaseId");
                        });

                    b.Navigation("Grupo");

                    b.Navigation("Ubicacion")
                        .IsRequired();
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Cuota", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", "Alumno")
                        .WithMany("Cuotas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Descuento", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId");

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Grupo", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Entrenador", "Entrenador")
                        .WithMany("Grupos")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Inscripcion", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joki.LogicaNegocio.Entidades.Clase", "Clase")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.ListaEspera", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joki.LogicaNegocio.Entidades.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.MaterialEjercicio", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Clase", "Clase")
                        .WithMany("MaterialesEjercicio")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Notificacion", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Cuota", "Cuota")
                        .WithMany("Pagos")
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuota");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.ParticipacionDesafio", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", "Alumno")
                        .WithMany("ParticipacionesDesafio")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joki.LogicaNegocio.Entidades.Desafio", "Desafio")
                        .WithMany("Participaciones")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Recompensa", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Desafio", "Desafio")
                        .WithMany("Recompensas")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.RecuperacionContrasena", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.SolicitudCupo", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Alumno", "Alumno")
                        .WithMany("SolicitudesCupo")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joki.LogicaNegocio.Entidades.Clase", "Clase")
                        .WithMany("SolicitudesCupo")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.HasOne("Joki.LogicaNegocio.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Joki.LogicaNegocio.ValueObjects.Apellido", "Apellido", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Apellido");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Joki.LogicaNegocio.ValueObjects.Celular", "Celular", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("nvarchar(9)")
                                .HasColumnName("Celular");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Joki.LogicaNegocio.ValueObjects.Contrasena", "Contrasena", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Contrasena");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Joki.LogicaNegocio.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Joki.LogicaNegocio.ValueObjects.Nombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nombre");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Apellido")
                        .IsRequired();

                    b.Navigation("Celular")
                        .IsRequired();

                    b.Navigation("Contrasena")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Clase", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Inscripciones");

                    b.Navigation("MaterialesEjercicio");

                    b.Navigation("SolicitudesCupo");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Cuota", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Desafio", b =>
                {
                    b.Navigation("Participaciones");

                    b.Navigation("Recompensas");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Grupo", b =>
                {
                    b.Navigation("Clases");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Recompensa", b =>
                {
                    b.Navigation("Beneficios");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Alumno", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Beneficios");

                    b.Navigation("Cuotas");

                    b.Navigation("Inscripciones");

                    b.Navigation("ParticipacionesDesafio");

                    b.Navigation("SolicitudesCupo");
                });

            modelBuilder.Entity("Joki.LogicaNegocio.Entidades.Entrenador", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
